### ISSUE TITLE
Не работает макрос gold

### ISSUE THREAD

**Issue by MoreBlood** [macrosoft/wotstat#7]
тратишь золото, а значение 0
кусок кода конфига
```html
"<textformat leading='3' tabstops='[73,100,168]'>Баланс:</font><tab><img src='img://gui/maps/icons/library/CreditsIcon-1.png' width='11' height='11' align='baseline' vspace='-2'> <font color='{{c:credits}}'>{{credits}}</font><tab>        <img src='img://gui/maps/icons/library/GoldIcon-1.png' width='11' height='11' align='baseline' vspace='2'><font color='#FFCC66'> {{gold}} </font></textformat><font>\n"
```

![image](https://cloud.githubusercontent.com/assets/10070770/8762317/6ccb21fa-2d7e-11e5-9255-4d1bd43f7a0a.png)

**Comment by rel1ct** [comment]
![default](https://cloud.githubusercontent.com/assets/10379802/8764867/d4f33bec-2dfa-11e5-8e84-eed9ff928b95.PNG)

**Comment by macrosoft** [comment]
как говорят в wg: ответ дан. тема закрыта.

**Comment by xmha97** [comment]
[I'm an inline-style link](data:text/plain;charset=utf-8,*.adobesc.com%0D%0A*.licenses.adobe.com)
